language: scala
scala:
- 2.11.11
jdk:
- openjdk8
script:
- sbt test

before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
     openssl aes-256-cbc -K $encrypted_2c5f221846d5_key -iv $encrypted_2c5f221846d5_iv -in secring.gpg.enc -out secring.gpg -d;
  fi

after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
     sbt compile publishSigned;
  fi
